export const kotigoriya = [
  {
    id: 1,
    img: "./imgAll/kotigoriya01.png",
    rank: "./imgAll/rank.png",
    title: "Women’s wear",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },  
  },
  {
    id: 2,
    img: "./imgAll/kotigoriya02.png",
    rank: "./imgAll/rank.png",
    title: "Men’s wear",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 3,
    img: "./imgAll/kotigoriya03.png",
    rank: "./imgAll/rank.png",
    title: "Kid’s wear",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 4,
    img: "./imgAll/kotigoriya04.png",
    rank: "./imgAll/rank.png",
    title: "Shoes",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 5,
    img: "./imgAll/kotigoriya05.png",
    rank: "./imgAll/rank.png",
    title: "Сумки",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 6,
    img: "./imgAll/kotigoriya06.png",
    rank: "./imgAll/rank.png",
    title: "Accessories",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 7,
    img: "./imgAll/kotigoriya07.png",
    rank: "./imgAll/rank.png",
    title: "Underwear",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 8,
    img: "./imgAll/kotigoriya08.png",
    rank: "./imgAll/rank.png",
    title: "Decorations",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 9,
    img: "./imgAll/kotigoriya09.png",
    rank: "./imgAll/rank.png",
    title: "Home textiles",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 10,
    img: "./imgAll/kotigoriya10.png",
    rank: "./imgAll/rank.png",
    title: "Wholesale",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
];
