export const data = [
  {
    id: 1,
    img: "./imgAll/brand4.png",
    rank: "./imgAll/rank.png",
    title: "Lorem ipsum dolor sit amet",
    comment:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit sed odio sed nascetur.",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 2,
    img: "./imgAll/brand3.png",
    rank: "./imgAll/rank.png",
    title: "Lorem ipsum dolor sit amet",
    comment:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit sed odio sed nascetur.",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 3,
    img: "./imgAll/brand2.png",
    rank: "./imgAll/rank.png",
    title: "Lorem ipsum dolor sit amet",
    comment:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit sed odio sed nascetur.",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
  {
    id: 4,
    img: "./imgAll/brand1.png",
    rank: "./imgAll/rank.png",
    title: "Lorem ipsum dolor sit amet",
    comment:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit sed odio sed nascetur.",
    price: 855,
    currency: "Y.E.",
    button: "ДОБАВИТ В КОРЗИНУ",
    counter: 1,
    size: {
      size28: 28,
      size30: 30,
      size32: 32,
      size34: 34,
      size36: 36,
      size38: 38,
    },
  },
];
